[package]
name = "logger_bot"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenvy = "0.15.7"
serenity = "0.12.5"
sqlx = { version = "0.8.6", features = ["runtime-tokio", "postgres", "macros"] }
tokio = { version = "1.49.0", features = ["rt-multi-thread"] }
